name = "DFD Hugo Minimal Test"
copyright = "© 2021-2022 Daniel F. Dickinson"
description = "Module for DFD's Hugo Minimal Test 'Theme'"

[module]
  [module.hugoVersion]
    min = "0.80.0"
    extended = false

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.wildtechgarden.ca/about/"
  copyright = "© 2021-2022 Daniel F. Dickinson"
  email = "dfdpublic@wildtechgarden.ca"
