name: weekly-external-link-check
on:
  schedule:
    # At 1:40 AM -0500 on each Thursday strictly check all external links (301 Moved is a failure not just a warning)
    - cron: '40 6 * * 4'
jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    steps:
      - name: "Build Site with Hugo and Audit"
        uses: danielfdickinson/build-audit-action-hugo-dfd@v0.2.1-beta.1
        with:
          upload-site-as: unminified-site
          use-lfs: false
          source-directory: exampleSite
  check-external-links:
    needs: build-unminified-site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run hugo-action-check-links
        uses: danielfdickinson/link-check-action-hugo-dfd@v0.2.5-beta.2
        with:
          canonical-root: https://example.com/
          check-external: true
          check-external-strict: true
          upload-logs-as: weekly-external-check-failure
          upload-logs-retention: 4
